### ISSUE TITLE
server returns HTTP 416 

### ISSUE THREAD

**Issue by hellt** [wjdp/htmltest#164]
# Describe the bug
A check on external link such as https://goreleaser.com/ produced HTTP 416 error which is a result of `Range: 0`?

Any methods to solve this false positive?

# To Reproduce
Create a link to https://goreleaser.com/ and run htmltest.

### .htmltest.yml

```yml
DirectoryPath: ./public
IgnoreURLs:
  - fonts.gstatic.com
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
IgnoreSSLVerify: true
IgnoreDirs:
  - overrides
  - page
IgnoreInternalEmptyHash: true
```

# Expected behaviour
While alternative solution (#162) to check external link is not yet implemented it would be nice to be able to ignore HTTP 416 specifically?

## Versions
 - OS: Mac OS 10.15.6
 - htmltest: latest
