### ISSUE TITLE
Support authenticating to targeted URLs

### ISSUE THREAD

**Issue by ITler** [wjdp/htmltest#206]
**Is your feature request related to a problem? Please describe.**
I would want to check pages that can only respond with a 200 after authentication.
It would need to be ensured that you send tokens only to the sites they would belong to.
Also credentials shouldn't be stored plain text in a configuration file or be passed plain text to the executable.

**Describe the solution you'd like**
I would like to see the possibility to provide a configuration like that:
``` yaml
auth:
  - site: <some site URL pattern>
    authType: basic
    userByEnvvar: <some envvar holding a user name>
    tokenByEnvvar: <some envvar holding a token>
  - site: <some other site URL pattern>
    authType: oauth2
    userByShellCommand: /path/to/my/script/retrieve-user.sh
    tokenByShellCommand: /path/to/my/script/retrieve-token.sh
```

**Describe alternatives you've considered**
There could be dozens of secret sources or auth types, but starting with reading credentials via envvars and allow basic and oauth2 authentication should provide a valuable base

**Additional context**
