### ISSUE TITLE
Option to omit Range header for certain URLs

### ISSUE THREAD

**Issue by vokal-isaac** [wjdp/htmltest#69]
Apparently, the `Range: bytes=0-0` header causes at least one server I've encountered to (inconsistently) respond with a 503 error.  It would be nice to have a way to work around this other than to ignore that URL.

This mostly yields a 503, but sometimes yields a 200 or 206:
```sh
curl -Ls \
    -H "User-Agent: Go-http-client/1.1" \
    -H "Range: bytes=0-0" \
    -H "Accept:" \
    -o /dev/null \
    -w "%{http_code}\n" \
    'http://www.teamfortress.com/'
```

**Comment by wjdp** [comment]
Thanks for the issue. I've heard of some servers not liking the range header but haven't had a URL to test against.

Couple of ideas:
- We could try `bytes=0-1`
- We could add an option to turn off this feature from all external URLs checked (not a good idea if you are linking to lots of files with some size)
- We could add a list of URLs to turn this header off for

I'm not overly happy with any one of those, if you've some better ideas post below :smile:

**Comment by vokal-isaac** [comment]
I tried `bytes=0-1` and still got a 503.  I came to the same conclusion about it being bad to turn it off for all external URLs.

Having an option just to modify/remove the `Range` header for certain URLs/patterns seems clunky, too.  Maybe something more generic, like a dictionary of URL patterns to custom headers, so that I could do something like
```yaml
CustomHeaderURLs:
  - "//www.teamfortress.com(/|$)":
      - "Range:"
  - "//some-other-site.net(/|$)":
      - "Range: bytes=0-1"
      - "Accept: text/html"
```

**Comment by wjdp** [comment]
Thinking about the following structure to allow custom options per URL:

```yaml
URLOptions:
  - Pattern: "example.com"
    HTTPHeaders:
      User-Agent: ABrowser/1
      Range: null
  - Pattern: "some-other-site.net"
    HTTPHeaders:
      Range: "bytes=0-1"
      Accept: text/html
```

The purview of `URLOptions` would later extend to include `IgnoreURLs` and `StripQueryExcludes`. This will collect 'per-url' options under one config option.
