### ISSUE TITLE
gorelaser + godownloader script for better CI/CD integration

### ISSUE THREAD

**Issue by caarlos0** [wjdp/htmltest#80]
it would be nice to have releases made in a way that [godownloader][] could generate scripts to install things on CI.

My workflow would be to to install both hugo and htmltest in that way:

```yaml
install:
- curl hugo.sh | bash
- curl htmltest.sh | bash
script:
- hugo
- htmltest ./public
```

With [goreleaser][] it is easy to do that, I can carry this issue on if you want.

[goreleaser]: https://goreleaser.com/
[godownloader]: https://github.com/goreleaser/godownloader
